### PR TITLE
fix(effort): tolerate object schema from Claude Code 2.1.115+

### PR DESCRIPTION
**Pull request by zelinewang**
## Problem

Since Claude Code 2.1.115+, the statusline crashes on every tick with:

```
[claude-hud] Error: level.toLowerCase is not a function
```

when a user has `display.showEffortLevel: true` in their config. The crash
only appears after upgrading Claude Code from 2.1.114 (or earlier) to
2.1.115+.

## Root cause

The original effort support (#471) was future-proofed for the case where
Claude Code would eventually expose the effort level via stdin JSON — but
because no schema existed yet, the type was guessed as a bare string:

```ts
effort?: string | null;
```

Claude Code 2.1.115+ actually added the field, but as an object:

```json
"effort": { "level": "max" },
"thinking": { "enabled": true },
"fast_mode": false
```

`resolveEffortLevel` then passes the whole object into `formatEffort`, which
invokes `level.toLowerCase()` on what is actually a `{ level: "max" }`
object — instant `TypeError`.

Evidence — live stdin dump from Claude Code 2.1.119 on macOS, Opus 4.7:

```json
{
  "session_id": "…",
  "version": "2.1.119",
  "model": { "id": "claude-opus-4-7", "display_name": "Opus 4.7" },
  "effort": { "level": "max" },
  "thinking": { "enabled": true },
  "fast_mode": false,
  …
}
```

## Fix

Accept both shapes (object with `level` string, or bare string) through a
tiny `extractEffortString` helper, and let any other truthy input fall
through to the existing `--effort` parent-process fallback rather than
throwing.

```ts
export type StdinEffortInput = string | StdinEffort | null | undefined;

export interface StdinEffort {
  level?: string | null;
  [key: string]: unknown;  // tolerate future additions like `budget`
}
```

The index signature keeps the type permissive — if Claude Code later adds
`effort.budget` or similar, no more breaking changes here.

## Tests

Added 10 tests in `tests/effort.test.js`:

- **Object schema (Claude Code 2.1.115+ shape)**
  - extracts `{ level: "max" }` → renders `●`
  - normalises uppercase level
  - handles all known levels inside objects
  - tolerates extra fields for forward-compat
  - falls through on missing / null / non-string `level`
- **Defensive handling (no crash)**
  - numeric / boolean / array inputs fall through rather than throwing

Result:

```
baseline: 486 pass, 0 fail
after   : 496 pass, 0 fail  (no regressions)
```

End-to-end verified by feeding the captured stdin payload to a locally-built
`dist/index.js`:

```
$ cat /tmp/hud-stdin-dump.json | node dist/index.js
[Opus 4.7 ●max] ██░░░░░░░░ 15% | zane | …
```

Exit code 0, effort bracket renders correctly.

## Notes

- `src/` only per CONTRIBUTING.md (CI rebuilds `dist/` on merge).
- Preserves backwards compatibility with the original PR #471 string shape
  in case any older Claude Code version still sends it or a user injects
  effort via another path.
- The `--effort` parent-process fallback path is unchanged and still acts
  as a safety net when stdin gives us nothing usable.

### CODE REVIEW

**Review by jarrodwatts — APPROVED** [review]
Security, quality, and maintainability review cleared. Local full suite passed in an isolated worktree (496 pass, 1 skipped), and GitHub CI is green.
